import { Metadata } from 'next';

// Contoh penggunaan Metadata sebagai Object
export const metadata: Metadata = {
  title: {    
    // Properti default berfungsi untuk seluruh halaman atau child route yang tidak mendefiniskan Metadata title
    default: 'Learn Next.js',

    /*
      Properti template berfungsi untuk membuat Dynamic Title menggunakan prefix atau suffix dan diterapkan hanya pada halaman 
      atau child route yang mendefinisikan Metadata title
    */  
    template: '%s | Next.js',
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
